@startuml example
interface condicionIVA {
    impuesto(monto)
}

class ConsumidorFinal {
    impuesto(monto)
}

class ResponsableInscripto {
    impuesto(monto)
}

class ResponsableNoInscripto {
    impuesto(monto)
}

class Cliente{
    saldo
    comprar(producto)
}

Cliente -left-> "1" condicionIVA

ConsumidorFinal .up.|> condicionIVA
ResponsableInscripto .up.|> condicionIVA
ResponsableNoInscripto .up.|> condicionIVA

class Producto {
    precio()
}

Cliente .down.> Producto

class ProductoEspecial {
    precio()
}

Producto <|-- ProductoEspecial

@enduml